# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-20 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('submissionTime', models.TextField()),
                ('targetClassifier', models.TextField()),
                ('networkAttack', models.TextField()),
                ('addAttackType', models.TextField()),
                ('results', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
